apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-patch-cm
spec:
  rules:
    - name: pCM1
      match:
        any:
        - resources:
            names:
              - demo-configmap
            kinds:
              - ConfigMap
      mutate:
        patchesJson6902: |-
          - path: "/data/topic"
            op: add
            value: "kyverno" 